<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Invoice {{ $invoice->invoice_no }}</title>
<style>
@page { margin: 28px 32px 52px; }
body { margin: 0; color: #2D3748; font-family: DejaVu Sans, sans-serif; font-size: 10pt; line-height: 1.35; }
table { width: 100%; border-collapse: collapse; } .primary, .label, h3 { color: #1F4E79; font-weight: bold; }
.title { margin: 12px 0 26px; color: #1F4E79; font-size: 16px; font-weight: bold; text-align: center; }
.brand { margin-bottom: 18px; } .brand td { vertical-align: middle; } .logo-cell { width: 35%; } .logo { max-width: 100%; max-height: 108px; }
.company { width: 65%; text-align: right; } .company-name { margin-bottom: 3px; color: #2D3748; font-weight: bold; }
.meta { margin-bottom: 14px; border: 1px solid #D9DEE5; table-layout: fixed; } .meta th, .meta td { width: 25%; padding: 6px 8px; background: #fff; border-right: 1px solid #D9DEE5; text-align: left; } .meta th { padding-bottom: 2px; color: #1F4E79; } .meta td { padding-top: 2px; }
.addresses { margin-bottom: 14px; border-collapse: separate; border-spacing: 6px 0; table-layout: fixed; } .addresses td { width: 50%; height: 105px; padding: 8px; border: 1px solid #D9DEE5; vertical-align: top; } h3 { margin: 0 0 6px; font-size: 10pt; } .muted { color: #6B7280; }
.items { margin-bottom: 14px; table-layout: fixed; } .items th { padding: 7px 5px; color: #fff; background: #1F4E79; border: 1px solid #1F4E79; text-align: left; } .items td { height: 42px; padding: 6px 5px; border: 1px solid #E5E7EB; vertical-align: top; } .items tr.even td { background: #FAFAFA; } .right { text-align: right !important; } .center { text-align: center !important; } .small { color: #6B7280; font-size: 9pt; }
.bottom { margin-bottom: 14px; table-layout: fixed; } .bottom > tbody > tr > td { width: 50%; padding: 8px; vertical-align: top; } .bank { border: 1px solid #D9DEE5; } .bank-row { margin: 2px 0; } .bank-row .label { display: inline-block; min-width: 92px; }
.summary td { padding: 4px 0; } .summary .divider td { border-bottom: 1px solid #D9DEE5; } .summary .grand td, .summary .due td { padding: 7px 0; color: #1F4E79; border-bottom: 1px solid #D9DEE5; font-weight: bold; }
.notes { padding: 8px; background: #F8FAFC; border: 1px solid #D9DEE5; } .footer { position: fixed; right: 0; bottom: -34px; left: 0; padding-top: 7px; color: #6B7280; border-top: 1px solid #D9DEE5; font-size: 9pt; text-align: center; }
</style></head><body>
@php
$company=$invoice->company; $customer=$invoice->customer; $bank=$company?->bankAccounts?->first();
$billingAddress=$customer?->billing_address ?: collect([$customer?->address_line1,$customer?->address_line2,$customer?->city,$customer?->postcode,$customer?->country])->filter()->join(', ');
$shippingAddress=$customer?->delivery_address ?: $billingAddress; $customerVat=$customer?->tax_number ?: $customer?->vat_number; $customerPhone=$customer?->phone ?: ($customer?->telephone_no ?: $customer?->mobile_no);
$subtotal=(float)$invoiceTotals['subtotal']; $discount=(float)$invoiceTotals['discount'];
@endphp
<div class="title">COMMERCIAL INVOICE</div>
<table class="brand"><tr><td class="logo-cell"><img class="logo" src="{{ filled($logoUrl) ? $logoUrl : public_path('images/logo.png') }}" alt="Company logo"></td><td class="company"><div class="company-name">{{ $company?->legal_business_name ?: ($company?->name ?: 'Company') }}</div>@if($company?->address)<div>{{ $company->address }}</div>@endif @if($company?->city || $company?->postcode)<div>{{ collect([$company?->city,$company?->postcode])->filter()->join(', ') }}</div>@endif @if($company?->country)<div>{{ $company->country }}</div>@endif @if($company?->vat_number)<div><span class="label">VAT No:</span> {{ $company->vat_number }}</div>@endif @if($company?->company_house_number)<div><span class="label">Company No:</span> {{ $company->company_house_number }}</div>@endif @if($company?->eori_number)<div><span class="label">EORI No:</span> {{ $company->eori_number }}</div>@endif @if($company?->email)<div><span class="label">Email:</span> {{ $company->email }}</div>@endif @if($company?->website)<div><span class="label">Website:</span> {{ $company->website }}</div>@endif @if($company?->business_phone_number || $company?->phone)<div><span class="label">Phone:</span> {{ $company?->business_phone_number ?: $company?->phone }}</div>@endif</td></tr></table>
<table class="meta"><thead><tr><th>Invoice No</th><th>Invoice Date</th><th>Due Date</th><th>Reference</th></tr></thead><tbody><tr><td>{{ $invoice->invoice_no }}</td><td>{{ $invoice->invoice_date?->format('d M Y') ?: '—' }}</td><td>{{ $invoice->due_date?->format('d M Y') ?: '—' }}</td><td>{{ $invoice->payment_note ?: '—' }}</td></tr></tbody></table>
<table class="addresses"><tr><td><h3>Invoice To</h3><strong>{{ $customer?->company_name ?: ($customer?->name ?: 'Walk-in Customer') }}</strong>@if($billingAddress)<div class="muted">{{ $billingAddress }}</div>@endif @if($customer?->email)<div class="muted">{{ $customer->email }}</div>@endif @if($customerVat)<div class="muted"><span class="label">VAT No:</span> {{ $customerVat }}</div>@endif</td><td><h3>Ship To</h3><strong>{{ $customer?->company_name ?: ($customer?->name ?: 'Walk-in Customer') }}</strong><div class="muted">{{ $shippingAddress ?: 'Same as invoice address' }}</div>@if($customer?->email)<div class="muted">{{ $customer->email }}</div>@endif @if($customerPhone)<div class="muted">{{ $customerPhone }}</div>@endif</td></tr></table>
<table class="items"><thead><tr><th style="width:5%">Sr</th><th style="width:30%">Description</th><th class="center" style="width:7%">Qty</th><th class="center" style="width:13%">Unit Price</th><th class="center" style="width:13%">Discount</th><th class="center" style="width:13%">Tax</th><th class="center" style="width:15%">Line Total</th></tr></thead><tbody>
@forelse($invoice->items as $item) @php $gross=round((float)$item->qty*(float)$item->rate,2); $lineDiscount=$subtotal>0?round($discount*$gross/$subtotal,2):0; $computedLine=$invoiceTotals['items'][$loop->index]??[]; $lineTax=(float)($computedLine['vat_amount']??$item->vat_amount); $lineTotal=(float)($computedLine['line_total']??$item->line_total)-$lineDiscount; $product=$item->productItem; @endphp
<tr class="{{ $loop->even ? 'even' : '' }}"><td>{{ $loop->iteration }}</td><td><strong>{{ $item->description ?: ($product?->name ?: 'Item') }}</strong>@if($product?->item_code)<div class="small">Code: {{ $product->item_code }}</div>@endif @if($product?->variation?->name)<div class="small">{{ $product->variation->name }}: {{ $product?->variationType?->name }}</div>@endif</td><td class="center">{{ rtrim(rtrim(number_format((float)$item->qty,3),'0'),'.') }}</td><td class="center">{{ app_money((float)$item->rate) }}</td><td class="center">{{ app_money($lineDiscount) }}</td><td class="center">{{ app_money($lineTax) }}</td><td class="center"><strong>{{ app_money($lineTotal) }}</strong></td></tr>
@empty <tr><td colspan="7">No invoice items</td></tr> @endforelse</tbody></table>
<table class="bottom"><tr><td class="bank"><h3>Company Bank Details</h3>@if($bank)<div class="bank-row"><span class="label">Bank Name:</span> {{ $bank->bank_name }}</div><div class="bank-row"><span class="label">Account Name:</span> {{ $bank->account_name }}</div><div class="bank-row"><span class="label">Account Number:</span> {{ $bank->account_number }}</div>@if($bank->sort_code)<div class="bank-row"><span class="label">Sort Code:</span> {{ $bank->sort_code }}</div>@endif @if($bank->iban)<div class="bank-row"><span class="label">IBAN:</span> {{ $bank->iban }}</div>@endif @if($bank->swift)<div class="bank-row"><span class="label">SWIFT:</span> {{ $bank->swift }}</div>@endif @else Bank details are available on request. @endif</td><td><table class="summary"><tr><td>Subtotal</td><td class="right">{{ app_money($subtotal) }}</td></tr><tr><td>Discount</td><td class="right">{{ app_money($discount) }}</td></tr><tr class="divider"><td>Tax</td><td class="right">{{ app_money((float)$invoiceTotals['vat_total']) }}</td></tr><tr class="grand"><td>Grand Total</td><td class="right">{{ app_money((float)$invoiceTotals['total']) }}</td></tr><tr class="divider"><td>Paid</td><td class="right">{{ app_money((float)$paidAmount) }}</td></tr><tr class="due"><td>Amount Due</td><td class="right">{{ app_money((float)$dueAmount) }}</td></tr></table></td></tr></table>
<div class="notes"><h3>Notes</h3>{{ filled($invoice->notes) ? $invoice->notes : '—' }}</div>
<div class="footer">This is a system-generated invoice and no signature is required.</div>
</body></html>
